### ISSUE TITLE
How to download the package?

### ISSUE THREAD

**Issue by AbdelazizHosny** [edreamleo/make-stub-files#24]
is there any command to download the package?

**Comment by edreamleo** [comment]
`pip install leo` will install of of Leo, including leoAst.py.

**Comment by edreamleo** [comment]
You can also install Leo from GitHub: `git clone https://github.com/leo-editor/leo-editor.git`

**Comment by edreamleo** [comment]
@AbdelazizHosny After spending so much time on make-stub-files, it turns out that I have never used in in practice!

Instead, I am now adding mypy annotations directly to Leo's code base using Leo's add-mypy-annotations command. I am improving this command as I use it. It automates most of the tedious work. I recommend using add-mypy-annptations rather than make-stub-files.

**Comment by AbdelazizHosny** [comment]
Thanks alot for your response, have a nice day!

**Comment by edreamleo** [comment]
@AbdelazizHosny You're welcome.

Note: I have just corrected the comment above to say "I am *now* adding mypy annotations directly to Leo's code base.
